### ISSUE TITLE
Remove extra image files.

### ISSUE THREAD

**Issue by prateikjena** [prateikjena/Hostel#1]
There are duplicate images in the assets. Help me removing them keeping the dependencies in mind. The build shouldn't fail.

**Comment by Zone-Infinity** [comment]
There are no duplicate images in the assets , do u want to remove the images which are not used ?

**Comment by padmalayajena** [comment]
Hi there,
I'm interested to work on this.

**Comment by prateikjena** [comment]
> There are no duplicate images in the assets, do u want to remove the images which are not used?

Thanks, @Zone-Infinity. But the issue is only for teaching purposes. I am assigning the issue to someone else.
